### ISSUE TITLE
Tying Symbols to colours

### ISSUE THREAD

**Issue by jaymeh** [maxcleme/beadcolors#12]
Over on [this](https://github.com/maxcleme/beadifier/issues/33) issue we spoke about having an option to translate each bead colour into a symbol on export. This gives more options when exporting and allows for different pdf patterns to be generated.

The task at hand now is to try and figure out how these symbols should be generated and we are throwing ideas around based on if we should use Emoji, SVG Fonts (FontAwesome etc) or Unicode characters.

This will involve generating a new API version with this new symbol item added as an option.

**Comment by jaymeh** [comment]
[symbols.log](https://github.com/maxcleme/beadcolors/files/4897373/symbols.log) - Full list of symbols.
[icon-list.txt](https://github.com/maxcleme/beadcolors/files/4897375/icon-list.txt) - Symbols that are left.

I think the biggest issue we may have here is in the event we get a bunch of new colours released and we run out of symbols for them. Keen to hear peoples thoughts :).

**Comment by jaymeh** [comment]
Hey @maxcleme ,

Just looking through this and wondered if you would also like me to take a look into creating the V3 api work for this? Noticed from your README that we should only MR with CSV's though so thought I'd ask before making a start.

Cheers.

**Comment by maxcleme** [comment]
@jaymeh 

Feel free to add new go files under [generation](https://github.com/maxcleme/beadcolors/tree/master/generation) folder.

Statements in the README are only to explain that all versions are generated based on the [raw](https://github.com/maxcleme/beadcolors/tree/master/raw) folder, so modifying [gen](https://github.com/maxcleme/beadcolors/tree/master/gen) folder doesn't make sense. 

Of course here we want to create a new version, so it's ok :)

**Comment by maxcleme** [comment]
In fact, I think we can stick with the initial set of symbols, having a unique symbol per palette is enough. We could easily distinguish it later on by using prefix and/or colors based on the palette origin.

eg: White Hama and Blue Perler could have the same symbol, however it could be rendered with prefix and/or colors based on Hama or Perler palettes.

However, as state, we need to think about maximum number of entries in a palette in order to support this behaviors.

**Comment by jaymeh** [comment]
@maxcleme I see, yes that could work as a first phase. We should have enough symbols per palette, the biggest one I could see was the new diamond dotz addition with ~480 colours. We have a full symbols list of around 700 so we should be ok.

I had a think about the overall approach for this last night and the only way I can see it working is to generate an additional file (possibly csv) somewhere inside the generation folder. This is generated automatically by assigning symbols to their colour code. We would then be able to lookup these associations when any new palette is added and regenerate the csv before pushing it into the gen folder.

Keen to hear your thoughts on this? 😃

**Comment by maxcleme** [comment]
New version is up and running. You can get v3 files here : 

https://beadcolors.eremes.xyz/gen/v3/[PALETTE_NAME].csv

Let's move on to beadifier repo for integration :)

**Comment by jaymeh** [comment]
Yeah, sounds good. Thanks 👍

**Comment by maxcleme** [comment]
If everything is fine, I guess we can close then :)

**Comment by jamiesykescreode** [comment]
Yeah, lets close this. Thanks
