### ISSUE TITLE
New Perler Colors 2019

### ISSUE THREAD

**Issue by HollyJannette7** [maxcleme/beadcolors#18]
[https://docs.google.com/spreadsheets/d/1u9CIj65P48rnmLr3yLIg096lRP-w-txcqBVfKnaCDZc/edit#gid=866910984](url)

I saw a thread somewhere on reddit about the colors and noticed BIORIO had the newer colors on his sheet as well. Since those are missing from Beadifier right now I wasn't sure if maybe those would help? Thanks for the awesome site btw! <3

**Comment by maxcleme** [comment]
Thanks for this @HollyJannette7,

I'll try to add them during next week! 

Cheers!

**Comment by maxcleme** [comment]
@HollyJannette7 

Up and running, new colors added to [beadcolors](https://beadcolors.eremes.xyz/)

Also available in [beadifier](https://beadifier.eremes.xyz/)

Feel free to verify if I added everything you wanted and close if satisfy :)

**Comment by HollyJannette7** [comment]
Awesome! You're the best, I'll check it out in a bit. Thank you!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by HollyJannette7** [comment]
Full Disclosure, I'm still new to Github. :p I'm not seeing the new colors on beadcolors or beadifier. I do see where you added it under the actions tab on here though. Is that what you were referring to when you said up and running? @maxcleme

**Comment by maxcleme** [comment]
@HollyJannette7 I guess you need to clean up your browser cache before seeing 'recent' update

**Comment by HollyJannette7** [comment]
That was it! haha thanks!! looks great
