### ISSUE TITLE
Perler Caps Palette?

### ISSUE THREAD

**Issue by Exodeca1** [maxcleme/beadcolors#20]
Really enjoy Beadifier a lot! Was wondering if it would be possible to add a Palette for just the Perler Caps? There's only 26 colors at the moment and it's not really known if Perler will continue support

**Comment by maxcleme** [comment]
@Exodeca1 

Definitely something that could happen, do you have all the color references? (in RGB or Hex?)

**Comment by Exodeca1** [comment]
Awesome! I've been using this template for the Perler Caps. Maybe just using the values already for the Perler colors would work? There's currently only 26 colors

Black | 323234
Blueberry Creme | 85A8E3
Blush | F99297
Brown | 674C44
Cheddar | FBB146
Cobalt | 0065B1
Cotton Candy | F479B0
Dark Gray | 585C61
Gray | 909497
Kiwi Lime | 69B845
Lagoon | 00A4AC
Light Brown | 936848
Light Gray | B3BAB8
Magenta | E04284
Orange | EB7B31
Plum | A75D9D
Prickly Pear | BBC938
Purple | 684B86
Red | B0353C
Rust | 995043
Sand | E5BE9E
Shamrock | 008F53
Tan | C5AC90
Toothpaste | 96D1D4
White | EAEFEE
Yellow | E7CE3E

**Comment by maxcleme** [comment]
You might be right since it seems to be produced by Perler itself. However I would like to be sure the color code are correct before adding those, might be misleading for people otherwise. Do you have the reference as well ? (not speaking about the color, but the reference of the color itself, eg: 80-15181, 80-15182, etc).

**Comment by Exodeca1** [comment]
Sure! This is from the Perler Website where they have the 750 caps beads listed

Black Beads_80-16086
Blueberry Cream Beads_80-16101
Blush Beads_80-16092 
Brown Beads_80-16105
Cheddar Beads_80-16093 
Cobalt Beads_80-16099
Cotton Candy Beads_80-16088
Dark Gray Beads_80-16111
Gray Beads_80-16110
Kiwi Beads_80-16096
Lagoon Beads_80-16098
Light Brown Beads_80-16106
Light Gray Beads_80-16109
Magenta Beads_80-16090
Orange Beads_80-16091 
Plum Beads_80-16103
Prickly Pear Beads_80-16094
Purple Beads_80-16102
Red Beads_80-16089
Rust Beads_80-16104
Sand Beads_80-16108
Shamrock Beads_80-16097
Tan Beads_80-16107
Toothpaste Beads_80-16100
White Beads_80-16087 
Yellow Beads_80-16095

**Comment by maxcleme** [comment]
@Exodeca1 

Perler caps support has been added and should also be available from beadcolors as well as beadifier.

Feel free to close this issue once it's ok on your side.

PS: You might have cache issue if you are trying right now, please make sure to clear everything :)

**Comment by Exodeca1** [comment]
Awesome! It's working great! Thank you for such an awesome tool!
