### ISSUE TITLE
Missing colour in perler mini section

### ISSUE THREAD

**Issue by timeframer** [maxcleme/beadcolors#21]
Perler also offers toasted marshmallow in the mini size, this should be included in the colour pallete.

**Comment by maxcleme** [comment]
@timeframer

Any color code reference? Hex or RGB? Link? 

Sorry to ask like this, but as Perler is not available where I live, it is kinda hard for me to 'guess' everything 😅

**Comment by timeframer** [comment]
https://www.perler.com/perler-storefront-catalog/products/categories/beads/2000-mini-beads-see-all-colors/
I belive the the code is F1E5D8 
Thanks so much for this program btw, got recomended it after hobby family went down, amazing site.

**Comment by maxcleme** [comment]
@timeframer thank for those kind word and those references, I'll try to add them during the week. I'll keep you in touch.

**Comment by timeframer** [comment]
Can i just add, not sure if its an easy addition but I would recomend a more logical ordering system for the colour selection? Either something to do with colour groups or alphabetically would be great

**Comment by maxcleme** [comment]
@timeframer It seems that Toasted Marshmallow color has already been sampled by Perlervault for classical bead size. I'm going to reuse its color code and add them for mini aswell.


Regarding color ordering, this is not related to this repository. It aims to centralize only the colors code.

**Comment by maxcleme** [comment]
@timeframer New color has been added and should also be available from [beadcolors](https://beadcolors.eremes.xyz/) as well as [beadifier](https://beadifier.eremes.xyz/).

Feel free to close this issue once it's ok on your side.

PS: You might have cache issue if you are trying right now, please make sure to clear everything :)

**Comment by maxcleme** [comment]
@timeframer Up ?

Can you check and close this if everything is fine for you ?
