### ISSUE TITLE
Perler Mini Template - A few changes possibly needed

### ISSUE THREAD

**Issue by Exodeca1** [maxcleme/beadcolors#24]
Hey I was using the template (Perler Minis + Artkal C Series) and it gave me P38 Magenta as a color. I can't find this color existing for the Perler Minis. I also noticed one color missing (P10 - Dark Green)

Missing 
P10 - Dark Green (Available for purchase on the Perler website)

Color Doesn't Exist 
P38 - Magenta (What's weird is this color exists for both Perler Caps & Regular Perler but not for minis)

Color may soon be out of production (Still exists on other websites but not on Perler's website for purchase)
P92 - Dark Gray

**Comment by maxcleme** [comment]
@Exodeca1 

Thanks for this feedback, I'm going to look at those and fix the file as well.

Are you able to confirm the following things ? 

P10: Dark Green: I agree, thankfully Perlervault already sample those which the following code : #007B4E, does it looks good to you ?
P38: Magenta: I might have screw up while merging all known sources, I guess it from the perler midi size, great catch.
P92: Already available here, can you confirm this as well ?

**Comment by Exodeca1** [comment]
Thanks for the quick response!
For P10 Dark Green, the #007B4E color looks good to me!
For P38 Magenta, I double checked and it's definitely not a color available as a mini
For P92 Dark Gray, it's available on the website! 

Thanks again!

**Comment by maxcleme** [comment]
Magenta in Perler Mini has been replaced with Dark Green.

Thanks again for feedback, please feel free to check it yourself and close if everything is fine.

Regards.

**Comment by Exodeca1** [comment]
Fantastic! Thank you for all the great work!
