### ISSUE TITLE
Missing Artkal C-Mini Colors

### ISSUE THREAD

**Issue by Exodeca1** [maxcleme/beadcolors#26]
Good Evening,

I went through the Artkal C-Series Mini Beads and found that these beads were missing from the palette. I've included the Color Name and RGB Values in case they were needed. 

They can be found on Artkal's Website: https://artkalfusebeads.com/pages/c-color-chart

C45 - Spring Green
#5DDB5G
R: 93 G: 219 B: 93

C55 - Conifer
#6CC241
R: 108 G: 194 B: 74

C57 - Fresh Red
#BC0423
R: 188 G: 4 B: 35

C59 - Scarlett
#531A23
R: 83 G: 26 B: 35

C60 - Sea Mist
#B2D7CE
R: 178 G: 215 B: 206

C61 - Feta
#F1EB9C
R: 241 G: 235 B: 156

C62 - Carnation
#FC3F3F
R: 252 G: 63 B: 63

C63 - Pink Pearl
#EABEDB
R: 234 G: 190 B: 219

C64 - Rose
#A50050
R: 165 G: 0 B: 80

C65 - Mango
#EF7E2E
R: 239 G: 126 B: 46

C66 - Wild Watermelon
#FC6C85
R: 252 G: 108 B: 133

C67 - Orchid
#B14EB5
R: 177 G: 78 B: 181

C68 - Toothpaste Blue
#69C2EE
R: 105 G: 194 B: 238

**Comment by maxcleme** [comment]
@Exodeca1

Thanks for feedback, I'll look at it in the following days. I'll keep you in touch. 

Regards.

**Comment by maxcleme** [comment]
I'm going to add everything except C60 since it is already here. I'll you in touch.

**Comment by maxcleme** [comment]
@Exodeca1 

Done in v0.30.2, as usual feel free to try this out and close if everything is fine.

Regards.

**Comment by Exodeca1** [comment]
Looks great to me! Thank you! :)
