### ISSUE TITLE
Hama midi vs Hama mini (and possibly maxi) color palettes

### ISSUE THREAD

**Issue by galaxyAbstractor** [maxcleme/beadcolors#30]
Currently there is only a single palette for Hama, but some colors only exists as Midi beads while they might be released as Mini later on. I noticed that after #29 is merged, the current palette contains all of the available Mini colors but are missing a few Midi colors. Currently if the missing Midi colors would be added to the single palette, you would have to remember to disable some colors each time when doing mini projects.

Missing Midi colors seems to be 72 - 74. They might be made available as Mini colors in the future, as this has been done before with some of the colors (released as Midi first and then as Mini later on).

Then there are some colors that are missing but I have hard time seeing being used in an application like this, but I mention them anyway if the purpose of this repo is completion, but they would be a headache to include. There are 55 - 57 that are glow-in-the-dark beads that would mess a design up if they were added automatically, and if you want to use them you'd probably design those areas manually where it makes sense to have glow-in-the-dark beads. 61 - 64 are metallic beads which might work or might not work, I've never seen them used and I am unsure if they create a non-shiny uniform color when ironed. If they do actually shine after being ironed, the same problem as as the glow-in-the-dark beads would be present, having weird shiny parts in a design where not intended. 54, 91 and 92 is not suitable either since these are mixed colors with glitter and stripes. 

The glow beads, metallic, glitter and stripes would only make sense if they are tagged as such and manual editing of a design was implemented in beadifier, as these kinds of beads could not be added automatically. They also pose some headaches as the product number is the same for different colors, impossible to determine rgb values etc.

Reference: https://www.hama.dk/media/102654/99199_artikel1.pdf

**Comment by maxcleme** [comment]
@galaxyAbstractor I'm 100% on this. I also had issues using 'ALL' the 'Hama' palette and I end up replacing beads manually afterwards.

TBH this repo aims to list all available beads colors etc, so I guess it is more something we should think and implement inside Beadifier (enable by default, etc).

But a category could definitively be added here, or maybe shard the Hama palette into N palettes ? (Something like the 4 distinct palettes for Artkal).

**Comment by maxcleme** [comment]
@galaxyAbstractor Any update ?
