### ISSUE TITLE
Missing Hama Colours

### ISSUE THREAD

**Issue by RetrolixusMcD** [maxcleme/beadcolors#33]
Hey There,

first off, amazing program, i used to use hobby.dk and thought i would be at a loss without it when it closed but your beadifier program is amazing!
colour wise there are the following hama ones missing from the list, is there a way to add them either myself or in general?

H15 - TRANSPARENT BLUE
H55 - GLOW IN THE DARK GREEN
H56 - GLOW IN THE DARK RED
H57 - GLOW IN THE DARK BLUE
H61 - GOLD
H62 - SILVER
H63 - BRONZE
H64 - PEARL
H72 - TRANSLUCENT PINK
H73 - TRANSLUCENT AQUA
H74 - TRANSLUCENT AQUA

thanks

Danny McD

**Comment by maxcleme** [comment]
@RetrolixusMcD 

Thank you for raising an issue here.

You're at the right place in order to deal with wrong/missing colors.

Regarding Hama,

All those new references could be added if color references are given (RGB values).

However, I would like to insist about Gold/Silver and maybe also Bronze/Pearl (never used) that side color are not the same as top/bottom color, and I had issue dealing with them in the past.

Are you able to find/sample/produce RGB values for all of those ?

Cheers!

**Comment by RetrolixusMcD** [comment]
Hey @maxcleme 

i can definitely see what you are saying about how the side walls are different colour to the top, unfortunately i have no experience in dealing with RGB etc and am definitely more of an end user! i have done a search and hama have the colours on their chart but no rgb values and can't see where they would be published. there is a google drive file from somebody but again the colours after are missing with the rgb values. is there a program where i could take a pic of the colour and then extract the values that way?

https://www.hama.dk/media/102647/colour-chart.pdf
https://drive.google.com/drive/folders/12ouYaF7mBuegQolus1oyr7o2nMNoIpmO

cheers

**Comment by maxcleme** [comment]
@RetrolixusMcD 

Sorry for late reply, I'm really and wll be busy this week and the following ones, I'll try to gather information regarding those and add them asap, I'll keep you in touch in this issue.

Don't hesitate to share RGB values as well if you find some.

Regards.

**Comment by RetrolixusMcD** [comment]
no apologies needed :)

**Comment by maxcleme** [comment]
@RetrolixusMcD Any update of those colors ? TBH I did not find anything related to them publicly available.

**Comment by Exodeca1** [comment]
> @RetrolixusMcD Any update of those colors ? TBH I did not find anything related to them publicly available.

From the PerlyPop App, this is the values I get

#487ED5 - R: 072 G: 126 B: 213 - H15 - Translucent Blue
#FAF8ED - R: 250 G: 248 B: 237 - H55 - Green (Glow in the Dark) [This seems wrong?]
#EDBF9F - R: 237 G: 191 B: 159 - H56 - Red (Glow in the Dark)
#C4D0E3 - R: 196 G: 208 B: 227 - H57 - Blue (Glow in the Dark)
#D99350 - R: 217 G: 147 B: 080 - H61 - Gold
#48474A - R: 072 G: 071 B: 074 - H62 - Silver
#42312F - R: 066 G: 049 B: 047 - H63 - Bronze
#EFEBE4 - R: 239 G: 235 B: 228 - H64 - Pearl
#F097B0 - R: 240 G: 151 B: 176 - H72 - Translucent Pink
#59AEF5 - R: 089 G: 174 B: 245 - H73 - Translucent Aqua
#5B55BD - R: 091 G: 085 B: 189 - H74 - Translucent Lilac

The only one that seems quite off is H55 - Green (Glow in the Dark)... it doesn't really look very green but I'm not too familiar with the Hama Palette set.

**Comment by Exodeca1** [comment]
Hmm... that H55 - Green (Glow in the Dark) may actually be accurate from what I see here on the Hama official website

https://www.hamabeads.com/product/1000-glow-in-the-dark-green-midi-hama-beads/

What an odd color!

**Comment by RetrolixusMcD** [comment]
Hey, no i haven't haven't had any luck, i did contact Hama but no reply. That may be accurate for the glow in the dark green as all of the glow ones have a totally different look to them when melted, same as the metallics

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by maxcleme** [comment]
@Exodeca1 Thanks again, I'll try to add them today.

**Comment by maxcleme** [comment]
@RetrolixusMcD 

Colors has been added and deployed.

I also credited @Exodeca1 instead since he/she's the one providing the colors values.

May I ask you to verify if everything is fine on your side and close this issue accordingly if so ?

Thanks again for contribution.

PS : Mad thanks to @Exodeca1 .

**Comment by RetrolixusMcD** [comment]
Amazing thanks to both of you, I'll have a look after back from work tomorrow 😊

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Exodeca1** [comment]
Glad I could help!
