### ISSUE TITLE
RGB & Hex Values for new Perler Colors (From the PerlyPop App)

### ISSUE THREAD

**Issue by Exodeca1** [maxcleme/beadcolors#34]
These values come from the PerlyPop App (only on iOS from what I read), not sure how accurate they are but it's better than nothing!

#8C8CA7 - R: 140 G: 140 B: 167 - P251 - Thistle
#5E6D7B - R: 094 G: 109 B: 123 - P252 - Slate Blue
#4C6388 - R: 076 G: 099 B: 136 - P253 - Denim
#9AA98E - R: 154 G: 169 B: 142 - P254 - Sage
#EFB79B - R: 239 G: 183 B: 155 - P255 - Orange Cream
#CA3B65 - R: 202 G: 059 B: 101 - P256 - Fruit Punch
#CB59B9 - R: 203 G: 089 B: 185 - P257 - Fuchsia
#714875 - R: 113 G: 072 B: 117 - P258 - Mulberry
#C8C85C - R: 200 G: 200 B: 092 - P259 - Slime
#988C8C - R: 152 G: 140 B: 140 - P260 - Stone
#14313B - R: 020 G: 049 B: 059 - P261 - Dark Spruce
#392928 - R: 057 G: 041 B: 040 - P262 - Cocoa

![Photo Jun 24, 9 26 46 PM](https://user-images.githubusercontent.com/65025997/123356388-a1d4e880-d535-11eb-8b9f-acae02caa8b7.png)
![Photo Jun 24, 9 26 53 PM](https://user-images.githubusercontent.com/65025997/123356389-a26d7f00-d535-11eb-8744-c1a369468878.png)

**Comment by maxcleme** [comment]
Thanks, will be added.

**Comment by Exodeca1** [comment]
Hey, not to be a bother but is there anything I can assist with to get these added to the site?

**Comment by maxcleme** [comment]
@Exodeca1 

Sorry for not handling this as fast as I wanted.

TBH the process is straighforward, and new lines needs to be added under the correct file in the `/raw` folder. The most complicated things is to make sure there is no duplicate, etc.

I might be able to tackle this next week, since I should be able to do it at work.

**Comment by maxcleme** [comment]
@Exodeca1 Currently building and merging, should be available publicly soon.

May I ask your help for this https://github.com/maxcleme/beadcolors/issues/33 aswell ? Are you able to find the color references in the same app ? Would be awesome.

**Comment by maxcleme** [comment]
@Exodeca1 Your color contribution has been merged and deployed.

Can you please check and confirm/close this issue if everything is fine ?

Thanks again.

**Comment by Exodeca1** [comment]
> @Exodeca1 Your color contribution has been merged and deployed.
> 
> Can you please check and confirm/close this issue if everything is fine ?
> 
> Thanks again.

Everything is great! Thanks! I'll check the PerlyPop app with regards to the other question
