### ISSUE TITLE
RGB value don't correspond to official sheet

### ISSUE THREAD

**Issue by Oznerologos** [maxcleme/beadcolors#39]
Hey there ! 

I am doing an app to calculate euclidian distance between two colors in order to find which bead color is closest to a given color (chances are this is exactly what you're doing with your beadifier but it's a school project and i found out about yours way too late ahah)

So I needed beads references and values and ended up on your beadcolors online page (which is really great 👌).
I gathered all values and made a json but i need the RGB values.
I converted the hex values to RGB and added them to my objects smoothly.

But then i compared the RGB values i got to the actual values given by the brand [Artkal ](https://cdn.shopify.com/s/files/1/1323/8195/files/Artkal-S-5mm-midi-beads-color-chart-2.jpg?v=1669019268)and they don't match. 

For example : 
your S01 - White - #EAEEF3 - r:234 g:238 b:243 while artkal gives r:255 g:255 b:255
your S02 - Burning Sand - #EE927C - r:238 g:146 b:124 while artkal gives r:255 g:263 b:139 (I realize as i write that 263 makes absolutly no sense)
your S03 - Tangerine - #FFA630 - r:255 g:166 b:48 while artkal gives r:246 g:176 b:76

Every color I checked at random was different
Do you have any idea where these differences could come from ? I don't how who to trust ahah (given that artkal sheet feels sketchy with its 263)

Hopping we can get to the bottom of this :)
Have a nice one !

<p>
<img src="https://user-images.githubusercontent.com/35913781/233382117-8b77320e-8308-4a4c-b44b-83714093d63c.png" width=200px display="inline">
<img src="https://user-images.githubusercontent.com/35913781/233382287-d59da7cb-3a62-4410-8140-af16010ebe26.png" width=200px  display="inline">
<img src="https://user-images.githubusercontent.com/35913781/233382373-4e5731b9-544e-4593-a1a3-9f4dc50036ec.png" width=200px  display="inline">
</p>

**Comment by Oznerologos** [comment]
just realized you could have got thr rgb values from your raw files 🤦‍♂️ (but the problem is still the same)

**Comment by maxcleme** [comment]
@Oznerologos Extremely late reply here, apologies. 

All the data from this repository are crunched and compiled based on several GSheets and references I could find on the internet (Reddit most likely). Some people out there use a color muse to gather this data. You can find more information by looking at the contributor name (last column from the website) in reddit (most likely in /r/beadsprites).

I'm not sure exactly when Artkal started providing their own value, but I'm pretty there weren't available at the time and the community came up with their own list.
