### ISSUE TITLE
Color for Hama - Mini

### ISSUE THREAD

**Issue by oliax** [maxcleme/beadcolors#40]
Hello,

Looks like color don't change with the choice of beads type.

Actually i set MINI type and the Beadifier still propose colors which're only available for MIDI beads. (H61 to H64, for example)

Thanks for your work anyway !

Regards, Olivier.

**Comment by maxcleme** [comment]
Hi, apologies for late reply.

There is actually only palette for Hama at the moment. You're genuinely the first one mentioning this! 

If we would like to come up with a hama_mini palette, do you have any references of those that only exist in mini?
