### ISSUE TITLE
Missing colours on Hama Palette

### ISSUE THREAD

**Issue by Tryk47** [maxcleme/beadcolors#44]
Hi 
the below colors are missing on the Bedifier HAMA colour palette.

H101 (Eucalyptus)
H102 (Forest Green)
H103 (Light Yellow)
H104 (Lime)
H105 (Light Apricot)
H106 (Light Lavender)
H107 (Lavender)

BR.
Tryk

**Comment by Tryk47** [comment]
seeing some of the other closed cases i saw you asked for RGB values. 
I took a printout from Pixel-Beads.net into Excel and got these colour values:

![image](https://github.com/user-attachments/assets/21b3dbb1-46ae-4eea-a7db-730036e94a54)

**Comment by maxcleme** [comment]
Thanks! I just added the new color references, they should be available on both beadcolors and beadifier in a few minutes!

**Comment by Tryk47** [comment]
wow, thanks for the fast reply and fix :D 
great support :)

**Comment by Tryk47** [comment]
i just checked https://beadifier.eremes.xyz/ 
they are not available here ?

is there something im missing ?

**Comment by maxcleme** [comment]
> i just checked https://beadifier.eremes.xyz/ they are not available here ?
> 
> is there something im missing ?

Probably cache issue, can you force refresh the cache of your browser?

![Screenshot 2024-07-25 at 10 49 45](https://github.com/user-attachments/assets/47ee70ad-532e-4e98-9e2d-e9275912b7b8)

**Comment by Tryk47** [comment]
thanks . 
It is working now. :)
