### ISSUE TITLE
Include a separate category/labels for the Artkal mini beads?

### ISSUE THREAD

**Issue by LlamaGodd** [maxcleme/beadcolors#6]

**Comment by maxcleme** [comment]
New 'Artkal C-2.6MM' has been added, can you please confirm and close this issue afterwards ?

**Comment by LlamaGodd** [comment]
Looks like it works! Thank you for improving on it!

**Comment by maxcleme** [comment]
Thanks to you! I don't have Artkal where I lived so I'm grateful for these
feedbacks!
