### ISSUE TITLE
Mini Perler Bead Palette

### ISSUE THREAD

**Issue by seotyeknom** [maxcleme/beadcolors#7]
Would there be a way to create a mini Perler bead label/category for ease of use? I can attach the palette I used earlier going by the Perler bead reference sheet. There aren't as many colors as with midi beads.

![miniperler-palette](https://user-images.githubusercontent.com/65378045/82001817-126abf80-962a-11ea-9be1-5ed7228706af.png)

**Comment by maxcleme** [comment]
@seotyeknom , I'm fine with it, we just need to find a suitable name.

**Comment by maxcleme** [comment]
@seotyeknom Perler mini palette has been added here. Support in beadifier should come soon.

Regards.

**Comment by maxcleme** [comment]
Latest palettes had been added, feel free to try this out and close if everything is fine on your side.

(You might have to clear your browser cache before seeing them).

Regards.
