### ISSUE TITLE
Open to Diamond Dotz for "3d Painting"?

### ISSUE THREAD

**Issue by dpalay** [maxcleme/beadcolors#8]
A similar art project is something referred to as "Diamond Painting" or "3d painting".  There are several brands of small plastic "drills" or "dots", As opposed to beads that are melted together, the dots are placed on a surface that has been covered in an adhesive.  
![image](https://user-images.githubusercontent.com/33780/85029731-38f8aa80-b142-11ea-997e-4f88d26801f9.png)

Are you open to hosting the colors for those here as well?

**Comment by dpalay** [comment]
#11 addresses this issue.  I did the work to pull the RGB values together.

**Comment by maxcleme** [comment]
MR has been merged, thanks for contribution ! 

However, could we work on the README to state that Diamond Paining is supported before closing this ?
