### ISSUE TITLE
readme has rgb_a when it should probably be rgb_r

### ISSUE THREAD

**Issue by dpalay** [maxcleme/beadcolors#9]
![image](https://user-images.githubusercontent.com/33780/85034017-3c426500-b147-11ea-968e-b2a7aeb69137.png)
Typically the "A" value when talking about rgba is the Alpha channel for transparency.  I believe these should all say rbg_r, meaning the red channel

**Comment by maxcleme** [comment]
@dpalay Great catch, gonna fix this.
